name: Trigger auto deployment for order-service-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ order-service ]
    paths:
    - '**'
    - '.github/workflows/order-service-app-AutoDeployTrigger-ee7bf688-37b1-48c5-9092-80227b571ae5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ORDERSERVICEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ORDERSERVICEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ORDERSERVICEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.ORDERSERVICEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORDERSERVICEAPP_REGISTRY_PASSWORD }}
          containerAppName: order-service-app
          resourceGroup: ctse-assi1
          imageToBuild: jeno1234/order-service-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


