name: CI/CD for Order Service

on:
  push:
    branches:
      - order-service
  pull_request:
    branches:
      - order-service

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -f ./ordermanagement/pom.xml clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ORDERDOCKERUSERNAME }}
          password: ${{ secrets.ORDERDOCKERPASSWORD }}

      - name: Build Docker image
        run: docker build -t jeno1234/ordermanagement:latest ./ordermanagement

      - name: Push Docker image to Docker Hub
        run: docker push jeno1234/ordermanagement:latest
