name: Trigger auto deployment for productservice-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ product-service ]
    paths:
    - '**'
    - '.github/workflows/productservice-app-AutoDeployTrigger-cc51c54f-22b1-4f6f-a31e-116509b9783b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PRODUCTSERVICEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRODUCTSERVICEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRODUCTSERVICEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.PRODUCTSERVICEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRODUCTSERVICEAPP_REGISTRY_PASSWORD }}
          containerAppName: productservice-app
          resourceGroup: ctse-assi1
          imageToBuild: chathuni2001/productservice-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


